services:
  ollama:
    image: ollama/ollama:latest
    container_name: basic-chatbot-setup-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  tts_service:
    build: ./TTS_service
    ports:
      - "8001:8001"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  stt_service:
    build: ./STT_service
    ports:
      - "8002:8002"
    volumes:
      - ./STT_service:/app  # Mount for easier debugging
    environment:
      - PYTHONUNBUFFERED=1  # Show logs immediately
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
    # Add healthcheck to verify service is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ollama-data:
  stt-models: